### ISSUE TITLE
Improve high-level view of process

### ISSUE THREAD

**Issue by bess** [pulibrary/vireo_transformation#12]
Edit this drawing to reflect more thorough description of process

https://docs.google.com/drawings/d/1vxmU-29ZuGspPTfTFD93ivV_-UFhjbFQMfbQv3X0xEM/edit

**Comment by kmcelwee** [comment]
![Screen Shot 2021-04-07 at 4.48.39 PM.png](https://images.zenhubusercontent.com/5e9efff74d7b4923426b5c0d/0de7eae9-a587-4391-9e7b-2292f8ed3099)

Reworked the google drawing (easier for me to use draw.io). New issues were created where necessary and existing issues were extended with notes from the historic python scripts.
