### ISSUE TITLE
Add a cover page to each approved thesis

### ISSUE THREAD

**Issue by bess** [pulibrary/vireo_transformation#3]
After processing, each thesis PDF should have a Princeton cover page pre-pended.

**Comment by kmcelwee** [comment]
Note from reading https://github.com/pulibrary/dspace-python/blob/main/thesiscentral-vireo/dataspace/python/enhanceAips.py: 
* We need to keep the original filename on the augmented PDF. For dataspace to ingest properly, `contents` needs to point to the correct file. The python script changes the original PDF to ORIG-{filename} and creates an augmented PDF with the original filename.
* The metadata_pu.xml will contain an element pdf.coverpage equal to SeniorThesisCoverPage, though this will probably be addressed when creating the pu metadata.
