### ISSUE TITLE
Apply embargoes

### ISSUE THREAD

**Issue by bess** [pulibrary/vireo_transformation#6]
Some theses have embargo data that must be applied. 

- [x] Record the embargo date
- [x] Record the mudd status (e.g., walk in only)
- [x] Be able to specify the embargo spreadsheet on the command line when invoking the process
- [x] Update dublin_core.xml with walking status (see comment below)

**Comment by kmcelwee** [comment]
The "Request Type" column in the restrictions spreadsheet is a red herring. Look only at the "Walk In Access" boolean and "Embargo Years" integer to determine whether to apply the appropriate metadata.

Here's the inherited logic to generate `metadata_pu.xml`:
```python
if (sub[self.embargo_idx] > 0):
       self._add_el(root, 'embargo.terms', "%d-07-01"  % (self.classyear + sub[self.embargo_idx]))
if (bool(sub[self.walkin_idx])):
       self._add_el(root, 'mudd.walkin', 'yes')
```
In other words, use `embargo.terms` to set the release date, and `mudd.walkin` to `yes` if the "Walk In Access" column says so.

We also want to update the `dublin_core.xml`. From Monika's scripts:
```python
    def  _adjust_dc_xml(self, root, sub):
        changed = False
        if (sub[self.walkin_idx]):
            if (root.find('dcvalue[@element="rights"]') is None):
                self._add_el(root, 'rights.accessRights', EnhanceAips.WALKIN_MSG)
                changed = True
        logging.debug(" _adjust_dc_xml: changed=%s" % unicode(changed))
        return changed

    def _add_el(self, root, metadata, value):
        logging.debug("XML add_el %s=%s" % (metadata, unicode(value)))
        splits = metadata.split('.')
        attrs = { 'element' : splits[0]}
        if len(splits) > 1:
            attrs['qualifier'] = splits[1]
        ET.SubElement(root, 'dcvalue', attrib=attrs).text = unicode(value)
```

The `WALIN_MSG` is:
```
Walk-in Access. This thesis can only be viewed on computer terminals at the <a href=http://mudd.princeton.edu>Mudd Manuscript Library</a>.
```
